# Generated by Django 6.0.4 on 2026-05-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('urgent', 'Терміновий')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'До виконання'), ('in_progress', 'В процесі'), ('review', 'На перевірці'), ('done', 'Виконано')], default='todo', max_length=20),
        ),
    ]
